macro(process_po_files)
    if(GETTEXT_MSGFMT_EXECUTABLE)
        file(GLOB _poFiles ${CMAKE_CURRENT_SOURCE_DIR}/*.po)
        gettext_create_translations("${CMAKE_CURRENT_SOURCE_DIR}/${PROJECT_NAME}.pot" ALL ${_poFiles})
    endif()
endmacro()
