name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt -y install extra-cmake-modules libboost-dev
    - name: Run cmake
      run: cmake .
    - name: Run make
      run: make
