name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
#  build-snap:
#    runs-on: ubuntu-18.04
#    steps:
#    - uses: actions/checkout@v2
#    - name: Install Snapcraft
#      uses: samuelmeuli/action-snapcraft@v1
#      with:
#        use_lxd: true
#        # `snapcraft export-login --snaps kradio --channels edge,stable -`, token valid for one year
##        snapcraft_token: ${{ secrets.SNAP_TOKEN_GH }}
#    - name: Build for Snapcraft
#      run: sg lxd -c 'snapcraft --use-lxd' && ls
#  build-tar:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - name: Install dependencies
#      run: sudo apt update && sudo apt -y --fix-missing install extra-cmake-modules libboost-dev qtmultimedia5-dev libkf5plasma-dev gettext libkf5xmlgui-dev libkf5kdelibs4support-dev ffmpeg libavcodec-dev libavformat-dev libavdevice-dev libavutil-dev libswscale-dev libpostproc-dev libswresample-dev libasound2-dev liblirc-dev libogg-dev libvorbis-dev libsndfile1-dev libmp3lame-dev libmms-dev appstream
#    - name: Run cmake
#      run: mkdir build && cmake -DCMAKE_INSTALL_PREFIX=./build -DCMAKE_BUILD_TYPE=RELEASE
#    - name: Run make
#      run: make
#    - name: Run make install
#      run: make install
#    - run: find ./build
#    - name: Tar build files
#      run: tar -cvf kradio5.tar ./build/*
#    - uses: actions/upload-artifact@v2
#      with:
#        name: kradio5
#        path: kradio5.tar
  build-appimage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt update && sudo apt -y --fix-missing install extra-cmake-modules libboost-dev qtmultimedia5-dev libkf5plasma-dev gettext libkf5xmlgui-dev libkf5kdelibs4support-dev ffmpeg libavcodec-dev libavformat-dev libavdevice-dev libavutil-dev libswscale-dev libpostproc-dev libswresample-dev libasound2-dev liblirc-dev libogg-dev libvorbis-dev libsndfile1-dev libmp3lame-dev libmms-dev appstream
    - name: Install appimage-builder
      run: sudo pip3 install appimage-builder
    - name: Install appimagetool
      run: |
        sudo apt install -y python3-pip python3-setuptools patchelf desktop-file-utils libgdk-pixbuf2.0-dev fakeroot
        sudo wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O /usr/local/bin/appimagetool
        sudo chmod +x /usr/local/bin/appimagetool
    - name: Run cmake
      run: cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=RELEASE
    - name: Run make
      run: make
    - name: Run make install
      run: make install DESTDIR=AppDir
    - name: Move desktop file
      run: mv AppDir/usr/share/applications/kradio5.desktop AppDir/usr/share/applications/org.kde.kradio5.desktop
    - run: find ./AppDir
    - name: Bundle AppImage
      run: appimage-builder --skip-test
    - run: find ./AppDir/ && ls -al .
    - name: Tar build files
      run: tar -cvf kradio5.tar ./AppDir
    - uses: actions/upload-artifact@v2
      with:
        name: kradio5
        path: kradio5.tar
    - uses: actions/upload-artifact@v2
      with:
        name: kradio5-latest-x86_64.AppImage
        path: kradio5-latest-x86_64.AppImage
